# Generated by Django 4.1.1 on 2022-10-05 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='reporter',
            new_name='user',
        ),
    ]
