# Generated by Django 4.1.1 on 2022-10-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_home_stu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stu',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
