# Generated by Django 4.1.1 on 2022-10-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_stu_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='stu',
            name='last_name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
